### PR TITLE
Performance improvments

### PR DESCRIPTION
**Pull request by EladKeyshawn**
I have encountered some bad design practices in our code, like static objects that shouldn't be static,  use of inappropriate or inefficient data structures. 
I'm trying to clean the code from those mistakes slowly. 😉 
Let me know if you have any more ideas related to that.

### CODE REVIEW

**Review by mhutti1 — COMMENTED** [review]
Looks fine to me 👍

**Review by mhutti1 — APPROVED** [review]

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn Should we merge and close this?

**Comment by EladKeyshawn** [comment]
I think so, I'll open a new once there are more improvements.

**Comment by kelson42** [comment]
@EladKeyshawn OK done

**Pull request merged**
