### PR TITLE
Added Kiwix icon to rate dialog

### PR DESCRIPTION
**Pull request by EladKeyshawn**

### CODE REVIEW

**Comment by kelson42** [comment]
How does that work for custom apps (which have a custom logo)?

**Comment by EladKeyshawn** [comment]
@Kelson42 Can you please elaborate on that since I'm not fully acquainted with this.

**Comment by kelson42** [comment]
We build custom apps like for example:
- https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikivoyage
- https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikimed

These apps use the same source code like Kiwix for Android. So if you set a Kiwix logo on the "rate us" dialog, then it will apply in the custom apps too and it should not. It should be the custom app logo - not the Kiwix logo.

Have a look to gen-custom-android-build.py to understand how these apps are built.

**Comment by EladKeyshawn** [comment]
Oh now i get it. they run on the same code base...
Still i don't understand what's the problem to keep the logo, since after all the organization is Kiwix.
Maybe i can change the playstore rating link itself to redirect to the appropriate app dynamically. :smile:

**Comment by kelson42** [comment]
@EladKeyshawn The link is good, it points to the custom app url. I have checked. But my question is "what about the logo now?"

**Comment by EladKeyshawn** [comment]
@kelson42 As i've said do you think we should change the logo? because the custom app is just configuration of Kiwix.

**Comment by kelson42** [comment]
@EladKeyshawn Yes, it should be probably the one of the app. If the one which is already in the app is not good enough, then we should (for all app) prepare a bigger one.

**Comment by EladKeyshawn** [comment]
@kelson42 yeah you are right. what i still need to know is how the icon path changes as a result from the gen-custom-android-build.py.

**Comment by kelson42** [comment]
@EladKeyshawn I'm not sure how it works exactly, but the analysis of the Python script should give you an answer pretty easily. I have open a dedicated ticket to follow that fix #34

**Pull request merged**
